[build]
  base = "web"
  publish = "web/build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_VERSION = "2.0.0"
  REACT_APP_NAME = "Generador de Documentos Funcionales - Web"
  GENERATE_SOURCEMAP = "false"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
